/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Leap {

public class CircleGesture : Gesture {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  public CircleGesture(global::System.IntPtr cPtr, bool cMemoryOwn) : base(LeapPINVOKE.CircleGesture_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(CircleGesture obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CircleGesture() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LeapPINVOKE.delete_CircleGesture(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static Gesture.GestureType ClassType() {
    Gesture.GestureType ret = (Gesture.GestureType)LeapPINVOKE.CircleGesture_ClassType();
    return ret;
  }

  public CircleGesture() : this(LeapPINVOKE.new_CircleGesture__SWIG_0(), true) {
  }

  public CircleGesture(Gesture rhs) : this(LeapPINVOKE.new_CircleGesture__SWIG_1(Gesture.getCPtr(rhs)), true) {
    if (LeapPINVOKE.SWIGPendingException.Pending) throw LeapPINVOKE.SWIGPendingException.Retrieve();
  }

  public Vector Center {
    get {
      global::System.IntPtr cPtr = LeapPINVOKE.CircleGesture_Center_get(swigCPtr);
      Vector ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vector(cPtr, true);
      return ret;
    } 
  }

  public Vector Normal {
    get {
      global::System.IntPtr cPtr = LeapPINVOKE.CircleGesture_Normal_get(swigCPtr);
      Vector ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vector(cPtr, true);
      return ret;
    } 
  }

  public float Progress {
    get {
      float ret = LeapPINVOKE.CircleGesture_Progress_get(swigCPtr);
      return ret;
    } 
  }

  public float Radius {
    get {
      float ret = LeapPINVOKE.CircleGesture_Radius_get(swigCPtr);
      return ret;
    } 
  }

  public Pointable Pointable {
    get {
      global::System.IntPtr cPtr = LeapPINVOKE.CircleGesture_Pointable_get(swigCPtr);
      Pointable ret = (cPtr == global::System.IntPtr.Zero) ? null : new Pointable(cPtr, true);
      return ret;
    } 
  }

}

}
