/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Leap {

public class DeviceList : Interface, System.Collections.Generic.IEnumerable<Device> {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  public DeviceList(global::System.IntPtr cPtr, bool cMemoryOwn) : base(LeapPINVOKE.DeviceList_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(DeviceList obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~DeviceList() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LeapPINVOKE.delete_DeviceList(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  private class DeviceListEnumerator : System.Collections.Generic.IEnumerator<Device> {
    private DeviceList _list;
    private int _index;
    public DeviceListEnumerator(DeviceList list) {
      _list = list;
      _index = -1;
    }
    public void Reset() {
      _index = -1;
    }
    public Device Current {
      get {
        return _list._operator_get(_index);
      }
    }
    object System.Collections.IEnumerator.Current {
      get {
        return this.Current;
      }
    }
    public bool MoveNext() {
      _index++;
      return (_index < _list.Count);
    }
    public void Dispose() {
      //No cleanup needed
    }
  }
  System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() {
    return this.GetEnumerator();
  }
  public System.Collections.Generic.IEnumerator<Device> GetEnumerator() {
    return new DeviceListEnumerator(this);
  }
  public Device this[int index] {
    get { return _operator_get(index); }
  }

  public DeviceList() : this(LeapPINVOKE.new_DeviceList(), true) {
  }

  private Device _operator_get(int index) {
    Device ret = new Device(LeapPINVOKE.DeviceList__operator_get(swigCPtr, index), true);
    return ret;
  }

  public DeviceList Append(DeviceList other) {
    DeviceList ret = new DeviceList(LeapPINVOKE.DeviceList_Append(swigCPtr, DeviceList.getCPtr(other)), false);
    if (LeapPINVOKE.SWIGPendingException.Pending) throw LeapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int Count {
    get {
      int ret = LeapPINVOKE.DeviceList_Count_get(swigCPtr);
      return ret;
    } 
  }

  public bool IsEmpty {
    get {
      bool ret = LeapPINVOKE.DeviceList_IsEmpty_get(swigCPtr);
      return ret;
    } 
  }

}

}
