/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Leap {

public class HandList : Interface, System.Collections.Generic.IEnumerable<Hand> {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  public HandList(global::System.IntPtr cPtr, bool cMemoryOwn) : base(LeapPINVOKE.HandList_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(HandList obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~HandList() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LeapPINVOKE.delete_HandList(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  private class HandListEnumerator : System.Collections.Generic.IEnumerator<Hand> {
    private HandList _list;
    private int _index;
    public HandListEnumerator(HandList list) {
      _list = list;
      _index = -1;
    }
    public void Reset() {
      _index = -1;
    }
    public Hand Current {
      get {
        return _list._operator_get(_index);
      }
    }
    object System.Collections.IEnumerator.Current {
      get {
        return this.Current;
      }
    }
    public bool MoveNext() {
      _index++;
      return (_index < _list.Count);
    }
    public void Dispose() {
      //No cleanup needed
    }
  }
  System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() {
    return this.GetEnumerator();
  }
  public System.Collections.Generic.IEnumerator<Hand> GetEnumerator() {
    return new HandListEnumerator(this);
  }
  public Hand this[int index] {
    get { return _operator_get(index); }
  }

  public HandList() : this(LeapPINVOKE.new_HandList(), true) {
  }

  private Hand _operator_get(int index) {
    Hand ret = new Hand(LeapPINVOKE.HandList__operator_get(swigCPtr, index), true);
    return ret;
  }

  public HandList Append(HandList other) {
    HandList ret = new HandList(LeapPINVOKE.HandList_Append(swigCPtr, HandList.getCPtr(other)), false);
    if (LeapPINVOKE.SWIGPendingException.Pending) throw LeapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int Count {
    get {
      int ret = LeapPINVOKE.HandList_Count_get(swigCPtr);
      return ret;
    } 
  }

  public bool IsEmpty {
    get {
      bool ret = LeapPINVOKE.HandList_IsEmpty_get(swigCPtr);
      return ret;
    } 
  }

  public Hand Leftmost {
    get {
      global::System.IntPtr cPtr = LeapPINVOKE.HandList_Leftmost_get(swigCPtr);
      Hand ret = (cPtr == global::System.IntPtr.Zero) ? null : new Hand(cPtr, true);
      return ret;
    } 
  }

  public Hand Rightmost {
    get {
      global::System.IntPtr cPtr = LeapPINVOKE.HandList_Rightmost_get(swigCPtr);
      Hand ret = (cPtr == global::System.IntPtr.Zero) ? null : new Hand(cPtr, true);
      return ret;
    } 
  }

  public Hand Frontmost {
    get {
      global::System.IntPtr cPtr = LeapPINVOKE.HandList_Frontmost_get(swigCPtr);
      Hand ret = (cPtr == global::System.IntPtr.Zero) ? null : new Hand(cPtr, true);
      return ret;
    } 
  }

}

}
