/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Leap {

public class Leap {
  public static float ePSILON {
    get {
      float ret = LeapPINVOKE.ePSILON_get();
      return ret;
    } 
  }

}

}
