/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Leap {

public class PointableList : Interface, System.Collections.Generic.IEnumerable<Pointable> {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  public PointableList(global::System.IntPtr cPtr, bool cMemoryOwn) : base(LeapPINVOKE.PointableList_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(PointableList obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PointableList() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LeapPINVOKE.delete_PointableList(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  private class PointableListEnumerator : System.Collections.Generic.IEnumerator<Pointable> {
    private PointableList _list;
    private int _index;
    public PointableListEnumerator(PointableList list) {
      _list = list;
      _index = -1;
    }
    public void Reset() {
      _index = -1;
    }
    public Pointable Current {
      get {
        return _list._operator_get(_index);
      }
    }
    object System.Collections.IEnumerator.Current {
      get {
        return this.Current;
      }
    }
    public bool MoveNext() {
      _index++;
      return (_index < _list.Count);
    }
    public void Dispose() {
      //No cleanup needed
    }
  }
  System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() {
    return this.GetEnumerator();
  }
  public System.Collections.Generic.IEnumerator<Pointable> GetEnumerator() {
    return new PointableListEnumerator(this);
  }
  public Pointable this[int index] {
    get { return _operator_get(index); }
  }

  public PointableList() : this(LeapPINVOKE.new_PointableList(), true) {
  }

  private Pointable _operator_get(int index) {
    Pointable ret = new Pointable(LeapPINVOKE.PointableList__operator_get(swigCPtr, index), true);
    return ret;
  }

  public PointableList Append(PointableList other) {
    PointableList ret = new PointableList(LeapPINVOKE.PointableList_Append__SWIG_0(swigCPtr, PointableList.getCPtr(other)), false);
    if (LeapPINVOKE.SWIGPendingException.Pending) throw LeapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PointableList Append(FingerList other) {
    PointableList ret = new PointableList(LeapPINVOKE.PointableList_Append__SWIG_1(swigCPtr, FingerList.getCPtr(other)), false);
    if (LeapPINVOKE.SWIGPendingException.Pending) throw LeapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PointableList Append(ToolList other) {
    PointableList ret = new PointableList(LeapPINVOKE.PointableList_Append__SWIG_2(swigCPtr, ToolList.getCPtr(other)), false);
    if (LeapPINVOKE.SWIGPendingException.Pending) throw LeapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PointableList Extended() {
    PointableList ret = new PointableList(LeapPINVOKE.PointableList_Extended(swigCPtr), true);
    return ret;
  }

  public int Count {
    get {
      int ret = LeapPINVOKE.PointableList_Count_get(swigCPtr);
      return ret;
    } 
  }

  public bool IsEmpty {
    get {
      bool ret = LeapPINVOKE.PointableList_IsEmpty_get(swigCPtr);
      return ret;
    } 
  }

  public Pointable Leftmost {
    get {
      global::System.IntPtr cPtr = LeapPINVOKE.PointableList_Leftmost_get(swigCPtr);
      Pointable ret = (cPtr == global::System.IntPtr.Zero) ? null : new Pointable(cPtr, true);
      return ret;
    } 
  }

  public Pointable Rightmost {
    get {
      global::System.IntPtr cPtr = LeapPINVOKE.PointableList_Rightmost_get(swigCPtr);
      Pointable ret = (cPtr == global::System.IntPtr.Zero) ? null : new Pointable(cPtr, true);
      return ret;
    } 
  }

  public Pointable Frontmost {
    get {
      global::System.IntPtr cPtr = LeapPINVOKE.PointableList_Frontmost_get(swigCPtr);
      Pointable ret = (cPtr == global::System.IntPtr.Zero) ? null : new Pointable(cPtr, true);
      return ret;
    } 
  }

}

}
