/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Leap {

public class SwipeGesture : Gesture {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  public SwipeGesture(global::System.IntPtr cPtr, bool cMemoryOwn) : base(LeapPINVOKE.SwipeGesture_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(SwipeGesture obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~SwipeGesture() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LeapPINVOKE.delete_SwipeGesture(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static Gesture.GestureType ClassType() {
    Gesture.GestureType ret = (Gesture.GestureType)LeapPINVOKE.SwipeGesture_ClassType();
    return ret;
  }

  public SwipeGesture() : this(LeapPINVOKE.new_SwipeGesture__SWIG_0(), true) {
  }

  public SwipeGesture(Gesture rhs) : this(LeapPINVOKE.new_SwipeGesture__SWIG_1(Gesture.getCPtr(rhs)), true) {
    if (LeapPINVOKE.SWIGPendingException.Pending) throw LeapPINVOKE.SWIGPendingException.Retrieve();
  }

  public Vector StartPosition {
    get {
      global::System.IntPtr cPtr = LeapPINVOKE.SwipeGesture_StartPosition_get(swigCPtr);
      Vector ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vector(cPtr, true);
      return ret;
    } 
  }

  public Vector Position {
    get {
      global::System.IntPtr cPtr = LeapPINVOKE.SwipeGesture_Position_get(swigCPtr);
      Vector ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vector(cPtr, true);
      return ret;
    } 
  }

  public Vector Direction {
    get {
      global::System.IntPtr cPtr = LeapPINVOKE.SwipeGesture_Direction_get(swigCPtr);
      Vector ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vector(cPtr, true);
      return ret;
    } 
  }

  public float Speed {
    get {
      float ret = LeapPINVOKE.SwipeGesture_Speed_get(swigCPtr);
      return ret;
    } 
  }

  public Pointable Pointable {
    get {
      global::System.IntPtr cPtr = LeapPINVOKE.SwipeGesture_Pointable_get(swigCPtr);
      Pointable ret = (cPtr == global::System.IntPtr.Zero) ? null : new Pointable(cPtr, true);
      return ret;
    } 
  }

}

}
